{{- if .Values.prometheusAdapter.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "blazorapp.fullname" . }}-prom-hpa
  labels:
    app: {{ include "blazorapp.name" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "blazorapp.fullname" . }}
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Pods
      pods:
        metric:
          name: nginx_requests_per_second
        target:
          type: AverageValue
          averageValue: "5"
{{- end }}
